import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { TanstackQueryProvider } from "@/components/providers/tanstack-query-provider";
import { TRPCReactProvider } from "@/utils/client";
import SimpleNavbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <TanstackQueryProvider>
        <TRPCReactProvider>
          <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
              <div className="min-h-screen flex flex-col">
                <SimpleNavbar />
                <main className="flex-1">
                  {children}
                </main>
              </div>
            </body>
          </html>
        </TRPCReactProvider>
      </TanstackQueryProvider>
    </ClerkProvider>
  );
}